#source 'https://github.com/roxiemobile/static-cocoa-frameworks.ios.git'

platform :ios, '9.0'
use_frameworks!

workspace '../RoxieMobile.ContentProviders/ContentProviders.xcworkspace'

def pod_from(name, *args)
  name = name.split('/').tap { |arr| arr[0] = "#{arr[0]}-SCF42" }.reject(&:empty?).join('/')
  pod(name, *args)
end


target 'ContentProviders.SQLite' do
  project '../RoxieMobile.ContentProviders/Sources/SQLite/ContentProviders.SQLite.xcodeproj'

  # Dependencies
  pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :tag => '1.0.0'
  pod 'Dispatch', :git => 'https://github.com/MamuninaNV/Dispatch.git', :branch => 'hotfix/2.0.4-patch.1'
  pod 'SwiftCommonsAbstractions', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsConcurrent', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsExtensions', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsLang', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsLogging', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsObjC', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SQLite.swift/SQLCipher', '~> 0.12.0'
end
